// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/view/404.vue')['default']
    Album: typeof import('./src/view/Album.vue')['default']
    App: typeof import('./src/App.vue')['default']
    Artist: typeof import('./src/view/Artist.vue')['default']
    ArtistInline: typeof import('./src/components/ArtistInline.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    ButtonIcon: typeof import('./src/components/ButtonIcon.vue')['default']
    Cover: typeof import('./src/components/Cover.vue')['default']
    CoverRow: typeof import('./src/components/CoverRow.vue')['default']
    DailyTracks: typeof import('./src/view/DailyTracks.vue')['default']
    DailyTracksCard: typeof import('./src/components/DailyTracksCard.vue')['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Explore: typeof import('./src/view/Explore.vue')['default']
    FMCard: typeof import('./src/components/FMCard.vue')['default']
    History: typeof import('./src/view/History.vue')['default']
    Home: typeof import('./src/view/Home.vue')['default']
    Library: typeof import('./src/view/Library.vue')['default']
    Login: typeof import('./src/view/Login.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    Playlist: typeof import('./src/view/Playlist.vue')['default']
    Scrollbar: typeof import('./src/components/Scrollbar.vue')['default']
    Search: typeof import('./src/view/Search.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Skeleton: typeof import('./src/components/Skeleton.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    Topbar: typeof import('./src/components/Topbar.vue')['default']
    Toplist: typeof import('./src/view/Toplist.vue')['default']
    TrackList: typeof import('./src/components/TrackList.vue')['default']
    TrackListItem: typeof import('./src/components/TrackListItem.vue')['default']
  }
}

export { }
